version: "3"

services:
  # prometheus
  prom:
    image: prom/prometheus
    container_name: prom
    ports:
      - 9090:9090
    networks:
      - monitor
    volumes:
      - prometheus:/etc/prometheus
    deploy:
      replicas: 1
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
  # grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitor
    deploy:
      replicas: 1
  # node-exporter
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    networks:
      - monitor
    deploy:
      replicas: 1
networks:
  monitor:
    driver: bridge
volumes:
  prometheus:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/prometheus